(define (problem door)
 (:domain door)
 (:objects  knight evil_knight prince - character
            bedroom armory hallway cell - room)
 (:protagonist knight)

 (:init (at knight cell)
        (at evil_knight gatehouse)
        (at prince bedroom)
        (has prince key)
        (in axe armory)
        (has evil_knight apple)
        (adjacent hallway cell)
        (adjacent hallway gatehouse)
        (adjacent hallway bedroom)
        (adjacent gatehouse armory)
        (intends knight (doorOpen))
        (intends evil_knight (not (doorOpen)))
        (intends evil_knight (has evil_knight key))
        (intends evil_knight (has evil_knight axe))
        (intends prince (has knight key))
 )

 (:bardichegoal
    (good
        (and (has knight key)
             (has knight apple)
             (doorOpen))
        (and (has knight axe)
             (has knight apple)
             (doorOpen))
    )
    (bad
        (and (has evil_knight key)
             (has evil_knight axe))
    )
 )
)
